name: Build

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      sonar_scan:
        required: false
        default: false
        type: boolean
      docker_push:
        required: false
        default: false
        type: boolean
      docker_build:
        required: false
        default: true
        type: boolean
      with_timestamp:
        required: false
        default: true
        type: boolean
      docker_file_location:
        required: false
        default: .
        type: string
      jdk_version:
        required: false
        default: '17'
        type: string
      jdk_distribution:
        required: false
        default: 'temurin'
        type: string
      run_tests:
        required: false
        default: true
        type: boolean
    outputs:
      tag:
        description: The generated docker tag
        value: ${{ jobs.build.outputs.tag }}

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      tag: ${{ steps.return-tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.branch }}

      - name: Checkout shared setup
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_PAT }}
          repository: IndependentIP/actions
          path: actions

      - if: ${{ github.event_name == 'pull_request' }}
        uses: ./actions/validate-pr

      - uses: ./actions/gradle-build
        with:
          jdk_version: ${{ inputs.jdk_version }}
          jdk_distribution: ${{ inputs.jdk_distribution }}
          run_tests: ${{ inputs.run_tests }}

      - if: ${{ inputs.sonar_scan }}
        uses: ./actions/sonarcloud-scan-gradle
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          sonarcloud_token: ${{ secrets.SONARCLOUD_TOKEN }}

      - uses: ./actions/get-tag
        with:
          branch: ${{ inputs.branch }}
          with_timestamp: ${{ inputs.with_timestamp }}

      - if: ${{ inputs.docker_build }}
        uses: ./actions/docker-build
        with:
          push: ${{ inputs.docker_push }}
          version: ${{ env.TAG }}
          google_credentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          docker_file_location: ${{ inputs.docker_file_location }}

      - id: return-tag
        run: echo "tag=${{ env.TAG }}" >> $GITHUB_OUTPUT
