name: Deploy

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'F8S-WI'

      - name: Checkout shared setup
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_PAT }}
          repository: IndependentIP/actions
          path: actions

      - uses: ./actions/gcloud
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}

      - uses: ./actions/setup-helm

      - uses: ./actions/pack-helm-chart
        with:
          version: ${{ inputs.tag }}
          charts_repo_url: ${{ secrets.FUGA_CHARTS_URL }}

      - uses: ./actions/phoenix-k8s-deploy
        with:
          environment: ${{ inputs.environment }}
          version: ${{ inputs.tag }}
          git_pat: ${{ secrets.GIT_PAT }}
          slack_webhook: ${{ secrets.PHOENIX_DEPLOYMENTS_WEBHOOK }}
