name: Deploy

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      environment:
        required: true
        type: string
      namespace:
        required: false
        type: string
      region:
        required: false
        type: string
        default: 'europe-west4'
      timeout:
        required: false
        type: string
        default: '600'
      fugernetes_branch:
        required: false
        type: string
        default: 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout shared setup
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_PAT }}
          repository: IndependentIP/actions
          path: actions

      - uses: ./actions/gcloud
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}

      - uses: ./actions/setup-helm

      - uses: ./actions/setup-helm-secrets
        with:
          age_secret: ${{ secrets.FUGA_AGE_SECRET }}

      - uses: ./actions/fugernetes-k8s-deploy
        with:
          environment: ${{ inputs.environment }}
          version: ${{ inputs.tag }}
          git_pat: ${{ secrets.GIT_PAT }}
          namespace: ${{ inputs.namespace }}
          region:  ${{ inputs.region }}
          timeout: ${{ inputs.timeout }}
          fugernetes_branch: ${{ inputs.fugernetes_branch }}
          slack_webhook: ${{ secrets.FUGERNETES_DEPLOYMENTS_WEBHOOK }}
